## NBA GAME PREDICTIONS

### Data Cleaning

In [1]:
import pandas as pd

df = pd.read_csv('nba_games.csv', index_col=0)

In [2]:
df.head()

mp   mp.1    fg    fga    fg%   3p   3pa    3p%    ft   fta  ...  \
0  240.0  240.0  39.0   81.0  0.481  6.0  20.0  0.300  14.0  18.0  ...   
1  240.0  240.0  36.0  100.0  0.360  7.0  31.0  0.226  16.0  19.0  ...   
2  240.0  240.0  37.0   85.0  0.435  8.0  19.0  0.421  17.0  23.0  ...   
3  240.0  240.0  41.0   89.0  0.461  8.0  21.0  0.381  17.0  19.0  ...   
4  240.0  240.0  27.0   86.0  0.314  6.0  26.0  0.231  15.0  20.0  ...   

   tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
0          22.8          29.0         178.0         111.0       DAL   
1          50.0          32.6         152.0         111.0       ATL   
2          20.0          30.9         148.0         116.0       SAS   
3          28.6          30.9         138.0         118.0       MIN   
4          16.8          30.9         157.0          90.0       MEM   

   total_opp  home_opp  season        date    won  
0         95         1    2016  2015-12-09   True  
1         98         0    2016  2015-12-09  False  
2        107         1    2018  2017-10-18  False  
3         99         0    2018  2017-10-18   True  
4         92         1    2021  2021-04-30  False  

[5 rows x 150 columns]

In [3]:
df = df.sort_values("date")

In [4]:
df = df.reset_index(drop=True)  # without the drop=True the old index gets added as a column to the df
df.head()

mp   mp.1    fg   fga    fg%   3p   3pa    3p%    ft   fta  ...  \
0  240.0  240.0  35.0  83.0  0.422  6.0  18.0  0.333  19.0  27.0  ...   
1  240.0  240.0  38.0  94.0  0.404  9.0  29.0  0.310  10.0  17.0  ...   
2  240.0  240.0  37.0  87.0  0.425  7.0  19.0  0.368  16.0  23.0  ...   
3  240.0  240.0  41.0  96.0  0.427  9.0  30.0  0.300  20.0  22.0  ...   
4  240.0  240.0  37.0  82.0  0.451  8.0  27.0  0.296  12.0  15.0  ...   

   tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
0          69.4          43.7         206.0         104.0       GSW   
1          53.2          34.6         162.0         104.0       CHI   
2          30.4          29.0         138.0         105.0       CLE   
3          37.5          38.9         201.0         120.0       NOP   
4          33.3          23.6         132.0         104.0       DET   

   total_opp  home_opp  season        date    won  
0        111         1    2016  2015-10-27  False  
1         97         1    2016  2015-10-27  False  
2         95         0    2016  2015-10-27   True  
3         95         0    2016  2015-10-27   True  
4        106         0    2016  2015-10-27  False  

[5 rows x 150 columns]

In [5]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [6]:
df

mp    fg   fga    fg%    3p   3pa    3p%    ft   fta    ft%  ...  \
0      240.0  35.0  83.0  0.422   6.0  18.0  0.333  19.0  27.0  0.704  ...   
1      240.0  38.0  94.0  0.404   9.0  29.0  0.310  10.0  17.0  0.588  ...   
2      240.0  37.0  87.0  0.425   7.0  19.0  0.368  16.0  23.0  0.696  ...   
3      240.0  41.0  96.0  0.427   9.0  30.0  0.300  20.0  22.0  0.909  ...   
4      240.0  37.0  82.0  0.451   8.0  27.0  0.296  12.0  15.0  0.800  ...   
...      ...   ...   ...    ...   ...   ...    ...   ...   ...    ...  ...   
17767  240.0  34.0  85.0  0.400  15.0  38.0  0.395  14.0  19.0  0.737  ...   
17768  240.0  41.0  88.0  0.466   9.0  40.0  0.225  13.0  15.0  0.867  ...   
17769  240.0  31.0  75.0  0.413  11.0  32.0  0.344  21.0  31.0  0.677  ...   
17770  240.0  34.0  80.0  0.425  11.0  28.0  0.393  11.0  12.0  0.917  ...   
17771  240.0  38.0  92.0  0.413  19.0  46.0  0.413   8.0   8.0  1.000  ...   

       tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
0              69.4          43.7         206.0         104.0       GSW   
1              53.2          34.6         162.0         104.0       CHI   
2              30.4          29.0         138.0         105.0       CLE   
3              37.5          38.9         201.0         120.0       NOP   
4              33.3          23.6         132.0         104.0       DET   
...             ...           ...           ...           ...       ...   
17767          42.9          36.3         133.0         112.0       GSW   
17768          45.0          94.4         300.0         112.0       BOS   
17769          33.3          36.2         222.0         107.0       GSW   
17770          33.3          31.5         186.0         111.0       GSW   
17771         100.0          42.6         141.0         126.0       BOS   

       total_opp  home_opp  season        date    won  
0            111         1    2016  2015-10-27  False  
1             97         1    2016  2015-10-27  False  
2             95         0    2016  2015-10-27   True  
3             95         0    2016  2015-10-27   True  
4            106         0    2016  2015-10-27  False  
...          ...       ...     ...         ...    ...  
17767        107         0    2022  2022-06-10  False  
17768         94         0    2022  2022-06-13   True  
17769        104         1    2022  2022-06-13  False  
17770        103         0    2022  2022-06-16  False  
17771         90         1    2022  2022-06-16   True  

[17772 rows x 147 columns]

In [7]:
# The target is the next value in the win column, the result of the NEXT game
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

# Apply the add_target function for a certain team by grouping the df by that team
df = df.groupby("team", group_keys=False).apply(add_target)

/var/folders/jw/63t02ylj29x9q8577qnttn000000gn/T/ipykernel_89972/2350846232.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/jw/63t02ylj29x9q8577qnttn000000gn/T/ipykernel_89972/2350846232.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/jw/63t02ylj29x9q8577qnttn000000gn/T/ipykernel_89972/2350846232.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, 

In [8]:
df[df["team"] == "HOU"]

mp    fg   fga    fg%    3p   3pa    3p%    ft   fta    ft%  ...  \
19     240.0  30.0  87.0  0.345   8.0  35.0  0.229  17.0  26.0  0.654  ...   
40     240.0  30.0  82.0  0.366   5.0  23.0  0.217  27.0  36.0  0.750  ...   
89     240.0  32.0  79.0  0.405  10.0  36.0  0.278  15.0  18.0  0.833  ...   
103    240.0  41.0  89.0  0.461   9.0  29.0  0.310  19.0  29.0  0.655  ...   
135    265.0  42.0  88.0  0.477  11.0  34.0  0.324  24.0  34.0  0.706  ...   
...      ...   ...   ...    ...   ...   ...    ...   ...   ...    ...  ...   
17440  240.0  41.0  97.0  0.423  17.0  45.0  0.378  18.0  26.0  0.692  ...   
17462  240.0  48.0  85.0  0.565  16.0  40.0  0.400  20.0  29.0  0.690  ...   
17480  240.0  40.0  99.0  0.404  11.0  43.0  0.256  14.0  25.0  0.560  ...   
17547  240.0  43.0  81.0  0.531  10.0  29.0  0.345  19.0  24.0  0.792  ...   
17564  240.0  41.0  89.0  0.461  17.0  46.0  0.370  15.0  20.0  0.750  ...   

       usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  total_opp  \
19             30.2         233.0         102.0       DEN        105   
40             40.2         152.0         104.0       GSW        112   
89             26.8         163.0         100.0       MIA        109   
103            32.6         155.0         112.0       OKC        105   
135            30.7         137.0         127.0       ORL        114   
...             ...           ...           ...       ...        ...   
17440          25.3         159.0         129.0       SAC        122   
17462          29.5         210.0         131.0       MIN        139   
17480          33.0         149.0         113.0       BRK        118   
17547          30.2         151.0         123.0       TOR        117   
17564          64.7         185.0         127.0       ATL        130   

       home_opp  season        date    won  target  
19            0    2016  2015-10-28  False   False  
40            0    2016  2015-10-30  False   False  
89            1    2016  2015-11-01  False    True  
103           0    2016  2015-11-02   True    True  
135           0    2016  2015-11-04   True    True  
...         ...     ...         ...    ...     ...  
17440         0    2022  2022-04-01  False   False  
17462         0    2022  2022-04-03  False   False  
17480         1    2022  2022-04-05  False   False  
17547         1    2022  2022-04-08  False   False  
17564         0    2022  2022-04-10  False     NaN  

[610 rows x 148 columns]

In [9]:
# Replace all of the null occurrences of null values in the target column 
df['target'][pd.isnull(df['target'])] = 2

/var/folders/jw/63t02ylj29x9q8577qnttn000000gn/T/ipykernel_89972/423589797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['target'][pd.isnull(df['target'])] = 2
/var/folders/jw/63t02ylj29x9q8577qnttn000000gn/T/ipykernel_89972/4235897

In [10]:
# Turn the target into a boolean integer value
df['target'] = df['target'].astype(int, errors='ignore')

In [11]:
df

mp    fg   fga    fg%    3p   3pa    3p%    ft   fta    ft%  ...  \
0      240.0  35.0  83.0  0.422   6.0  18.0  0.333  19.0  27.0  0.704  ...   
1      240.0  38.0  94.0  0.404   9.0  29.0  0.310  10.0  17.0  0.588  ...   
2      240.0  37.0  87.0  0.425   7.0  19.0  0.368  16.0  23.0  0.696  ...   
3      240.0  41.0  96.0  0.427   9.0  30.0  0.300  20.0  22.0  0.909  ...   
4      240.0  37.0  82.0  0.451   8.0  27.0  0.296  12.0  15.0  0.800  ...   
...      ...   ...   ...    ...   ...   ...    ...   ...   ...    ...  ...   
17767  240.0  34.0  85.0  0.400  15.0  38.0  0.395  14.0  19.0  0.737  ...   
17768  240.0  41.0  88.0  0.466   9.0  40.0  0.225  13.0  15.0  0.867  ...   
17769  240.0  31.0  75.0  0.413  11.0  32.0  0.344  21.0  31.0  0.677  ...   
17770  240.0  34.0  80.0  0.425  11.0  28.0  0.393  11.0  12.0  0.917  ...   
17771  240.0  38.0  92.0  0.413  19.0  46.0  0.413   8.0   8.0  1.000  ...   

       usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  total_opp  \
0              43.7         206.0         104.0       GSW        111   
1              34.6         162.0         104.0       CHI         97   
2              29.0         138.0         105.0       CLE         95   
3              38.9         201.0         120.0       NOP         95   
4              23.6         132.0         104.0       DET        106   
...             ...           ...           ...       ...        ...   
17767          36.3         133.0         112.0       GSW        107   
17768          94.4         300.0         112.0       BOS         94   
17769          36.2         222.0         107.0       GSW        104   
17770          31.5         186.0         111.0       GSW        103   
17771          42.6         141.0         126.0       BOS         90   

       home_opp  season        date    won  target  
0             1    2016  2015-10-27  False       0  
1             1    2016  2015-10-27  False       1  
2             0    2016  2015-10-27   True       1  
3             0    2016  2015-10-27   True       1  
4             0    2016  2015-10-27  False       1  
...         ...     ...         ...    ...     ...  
17767         0    2022  2022-06-10  False       0  
17768         0    2022  2022-06-13   True       1  
17769         1    2022  2022-06-13  False       0  
17770         0    2022  2022-06-16  False       2  
17771         1    2022  2022-06-16   True       2  

[17772 rows x 148 columns]

In [12]:
# Check if there is a class imbalance
df["won"].value_counts()

won
False    8886
True     8886
Name: count, dtype: int64

In [13]:
df["target"].value_counts()

target
1    8872
0    8870
2      30
Name: count, dtype: int64

In [14]:
null_counts = df.isnull().sum()  # Check to see if any columns in the datagrame have a null value. 
null_counts = null_counts[null_counts > 0]
null_counts

+/-             17772
mp_max          17772
mp_max.1        17772
+/-_opp         17772
mp_max_opp      17772
mp_max_opp.1    17772
dtype: int64

In [15]:
# Since these values are null almost always, we can just get rid of all of them
valid_columns = df.columns[~df.columns.isin(null_counts.index)]

In [16]:
df.columns, valid_columns

(Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
        ...
        'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
        'home_opp', 'season', 'date', 'won', 'target'],
       dtype='object', length=148),
 Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
        ...
        'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
        'home_opp', 'season', 'date', 'won', 'target'],
       dtype='object', length=142))

We got rid of these values, now the length of the columns in the dataframe decresed from 148 to 142

In [17]:
df = df[valid_columns].copy()   # Copy allows us to create a new dataframe instead of getting a part of another one.

In [18]:
df

mp    fg   fga    fg%    3p   3pa    3p%    ft   fta    ft%  ...  \
0      240.0  35.0  83.0  0.422   6.0  18.0  0.333  19.0  27.0  0.704  ...   
1      240.0  38.0  94.0  0.404   9.0  29.0  0.310  10.0  17.0  0.588  ...   
2      240.0  37.0  87.0  0.425   7.0  19.0  0.368  16.0  23.0  0.696  ...   
3      240.0  41.0  96.0  0.427   9.0  30.0  0.300  20.0  22.0  0.909  ...   
4      240.0  37.0  82.0  0.451   8.0  27.0  0.296  12.0  15.0  0.800  ...   
...      ...   ...   ...    ...   ...   ...    ...   ...   ...    ...  ...   
17767  240.0  34.0  85.0  0.400  15.0  38.0  0.395  14.0  19.0  0.737  ...   
17768  240.0  41.0  88.0  0.466   9.0  40.0  0.225  13.0  15.0  0.867  ...   
17769  240.0  31.0  75.0  0.413  11.0  32.0  0.344  21.0  31.0  0.677  ...   
17770  240.0  34.0  80.0  0.425  11.0  28.0  0.393  11.0  12.0  0.917  ...   
17771  240.0  38.0  92.0  0.413  19.0  46.0  0.413   8.0   8.0  1.000  ...   

       usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  total_opp  \
0              43.7         206.0         104.0       GSW        111   
1              34.6         162.0         104.0       CHI         97   
2              29.0         138.0         105.0       CLE         95   
3              38.9         201.0         120.0       NOP         95   
4              23.6         132.0         104.0       DET        106   
...             ...           ...           ...       ...        ...   
17767          36.3         133.0         112.0       GSW        107   
17768          94.4         300.0         112.0       BOS         94   
17769          36.2         222.0         107.0       GSW        104   
17770          31.5         186.0         111.0       GSW        103   
17771          42.6         141.0         126.0       BOS         90   

       home_opp  season        date    won  target  
0             1    2016  2015-10-27  False       0  
1             1    2016  2015-10-27  False       1  
2             0    2016  2015-10-27   True       1  
3             0    2016  2015-10-27   True       1  
4             0    2016  2015-10-27  False       1  
...         ...     ...         ...    ...     ...  
17767         0    2022  2022-06-10  False       0  
17768         0    2022  2022-06-13   True       1  
17769         1    2022  2022-06-13  False       0  
17770         0    2022  2022-06-16  False       2  
17771         1    2022  2022-06-16   True       2  

[17772 rows x 142 columns]

### Machine Learning

Our current dataframe has a large number of columns. This is a problem because it can create a lot of noise or overfitting and mess with our results. Before going into the machine learning, we will use a feature selector that will allow us to get the important columns. 

In [19]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

# We have time-series data, so we need to make sure that we use a split that accounts for this
rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr,     # The model being used
                                n_features_to_select=30,    # The amount of columns we want left in our data
                                direction="forward",    # This will pick the best feature first and then continue to pick until we have 30
                                cv=split)   #   Time series split used for cross-validation

In [20]:
# Ridge Regression works best when numbers are normalized within a range, in this case we will normalize the scores between 0 and 1
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]   # These features cant really be turned into numbers, so we will remove them for now

In [ ]:
selected_colums = df.columns[~df.columns.isin(removed_columns)]

In [22]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_colums] = scaler.fit_transform(df[selected_colums])

In [23]:
df

mp        fg       fga       fg%        3p       3pa       3p%  \
0      0.0  0.363636  0.338235  0.366029  0.206897  0.212121  0.395487   
1      0.0  0.431818  0.500000  0.322967  0.310345  0.378788  0.368171   
2      0.0  0.409091  0.397059  0.373206  0.241379  0.227273  0.437055   
3      0.0  0.500000  0.529412  0.377990  0.310345  0.393939  0.356295   
4      0.0  0.409091  0.323529  0.435407  0.275862  0.348485  0.351544   
...    ...       ...       ...       ...       ...       ...       ...   
17767  0.0  0.340909  0.367647  0.313397  0.517241  0.515152  0.469121   
17768  0.0  0.500000  0.411765  0.471292  0.310345  0.545455  0.267221   
17769  0.0  0.272727  0.220588  0.344498  0.379310  0.424242  0.408551   
17770  0.0  0.340909  0.294118  0.373206  0.379310  0.363636  0.466746   
17771  0.0  0.431818  0.470588  0.344498  0.655172  0.636364  0.490499   

             ft       fta       ft%  ...  usg%_max_opp  ortg_max_opp  \
0      0.418605  0.412698  0.654609  ...      0.277279      0.554502   
1      0.209302  0.253968  0.519253  ...      0.160462      0.345972   
2      0.348837  0.349206  0.645274  ...      0.088575      0.232227   
3      0.441860  0.333333  0.893816  ...      0.215661      0.530806   
4      0.255814  0.222222  0.766628  ...      0.019255      0.203791   
...         ...       ...       ...  ...           ...           ...   
17767  0.302326  0.285714  0.693116  ...      0.182285      0.208531   
17768  0.279070  0.222222  0.844807  ...      0.928113      1.000000   
17769  0.465116  0.476190  0.623104  ...      0.181001      0.630332   
17770  0.232558  0.174603  0.903151  ...      0.120668      0.459716   
17771  0.162791  0.111111  1.000000  ...      0.263158      0.246445   

       drtg_max_opp  team_opp  total_opp  home_opp  season        date    won  \
0          0.317647       GSW   0.451923       1.0    2016  2015-10-27  False   
1          0.317647       CHI   0.317308       1.0    2016  2015-10-27  False   
2          0.329412       CLE   0.298077       0.0    2016  2015-10-27   True   
3          0.505882       NOP   0.298077       0.0    2016  2015-10-27   True   
4          0.317647       DET   0.403846       0.0    2016  2015-10-27  False   
...             ...       ...        ...       ...     ...         ...    ...   
17767      0.411765       GSW   0.413462       0.0    2022  2022-06-10  False   
17768      0.411765       BOS   0.288462       0.0    2022  2022-06-13   True   
17769      0.352941       GSW   0.384615       1.0    2022  2022-06-13  False   
17770      0.400000       GSW   0.375000       0.0    2022  2022-06-16  False   
17771      0.576471       BOS   0.250000       1.0    2022  2022-06-16   True   

       target  
0           0  
1           1  
2           1  
3           1  
4           1  
...       ...  
17767       0  
17768       1  
17769       0  
17770       2  
17771       2  

[17772 rows x 142 columns]

In [24]:
sfs.fit(df[selected_colums], df['target'])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [25]:
predictors = list(selected_colums[sfs.get_support()])

In [26]:
predictors

['mp',
 'fg%',
 '3p%',
 'orb',
 'ts%',
 'usg%',
 '3p%_max',
 'ft_max',
 'fta_max',
 '+/-_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'usg%_max',
 'mp_opp',
 'fg_opp',
 '3p_opp',
 'ft%_opp',
 'blk_opp',
 'usg%_opp',
 'fga_max_opp',
 '3p_max_opp',
 'ft_max_opp',
 'ft%_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 'drb%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp']

These features have been selected as the best to pick by the Feature Selector for Ridge Regression.

The one's with 'max' indicate the player on the team that shot the best.

In [27]:
def backtest(data, model, predictors, start=2, step=1):
    # Split data by season. Uses past season to predict future seasons. 
    all_predictions = []

    seasons = sorted(data["season"].unique())

    # This loop goes from the third season onwards to the last season
    # The training data is split as all the seasons before, and the test is that season
    for i in range(start, len(seasons), step):
        season = seasons[i]

        train = data[data["season"] < season]
        test = data[data["season"] == season]

        model.fit(train[predictors], train['target'])

        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)

        combined = pd.concat([test['target'], preds], axis=1)
        combined.columns = ["actual", "prediction"]

        all_predictions.append(combined)
    
    return pd.concat(all_predictions)

In [28]:
predictions = backtest(df, rr, predictors)

In [29]:
predictions

actual  prediction
5250        1           1
5251        1           1
5252        0           0
5253        1           0
5254        0           1
...       ...         ...
17767       0           0
17768       1           1
17769       0           1
17770       2           1
17771       2           1

[12522 rows x 2 columns]

In [30]:
# Now let's make a metric to measure the similatirty of these numbers
from sklearn.metrics import accuracy_score

accuracy_score(predictions["actual"], predictions["prediction"])

0.5471969333972209

In [31]:
# Could get a little better score by removing the 2s 
from sklearn.metrics import accuracy_score

sample_predictions = predictions[predictions["actual"] != 2]
accuracy_score(sample_predictions["actual"], sample_predictions["prediction"])

0.5485110470701249

## Improving the Model

In basketball there are many other nuances that are not accounted for fully in our previous model. The model would have much more accurate predictions if it was given better guidelines to predict on. 

For example, we need to have an accuracy that's higher than the % of home teams that win the games or else, we could just use that as our metric instead of doing ML.

In [32]:
df.groupby("home", group_keys=False).apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

/var/folders/jw/63t02ylj29x9q8577qnttn000000gn/T/ipykernel_89972/1197928991.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("home", group_keys=False).apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])


home
0.0    0.428314
1.0    0.571686
dtype: float64

In [33]:
df_rolling = df[list(selected_colums) + ["won", "team", "season"]]

In [34]:
# We can create a weighted average of how a team performed in their last 10 games, as opposed to just the one game that we are using now
def find_team_averages(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

DataError: Cannot aggregate non-numeric type: object

In [ ]:
df_rolling

mp        fg       fga       fg%        3p       3pa       3p%  \
0      0.0  0.363636  0.338235  0.366029  0.206897  0.212121  0.395487   
1      0.0  0.431818  0.500000  0.322967  0.310345  0.378788  0.368171   
2      0.0  0.409091  0.397059  0.373206  0.241379  0.227273  0.437055   
3      0.0  0.500000  0.529412  0.377990  0.310345  0.393939  0.356295   
4      0.0  0.409091  0.323529  0.435407  0.275862  0.348485  0.351544   
...    ...       ...       ...       ...       ...       ...       ...   
17767  0.0  0.340909  0.367647  0.313397  0.517241  0.515152  0.469121   
17768  0.0  0.500000  0.411765  0.471292  0.310345  0.545455  0.267221   
17769  0.0  0.272727  0.220588  0.344498  0.379310  0.424242  0.408551   
17770  0.0  0.340909  0.294118  0.373206  0.379310  0.363636  0.466746   
17771  0.0  0.431818  0.470588  0.344498  0.655172  0.636364  0.490499   

             ft       fta       ft%  ...  blk%_max_opp  tov%_max_opp  \
0      0.418605  0.412698  0.654609  ...         0.079      0.679245   
1      0.209302  0.253968  0.519253  ...         0.140      0.509434   
2      0.348837  0.349206  0.645274  ...         0.185      0.270440   
3      0.441860  0.333333  0.893816  ...         0.063      0.344864   
4      0.255814  0.222222  0.766628  ...         0.047      0.300839   
...         ...       ...       ...  ...           ...           ...   
17767  0.302326  0.285714  0.693116  ...         0.103      0.401468   
17768  0.279070  0.222222  0.844807  ...         0.124      0.423480   
17769  0.465116  0.476190  0.623104  ...         0.076      0.300839   
17770  0.232558  0.174603  0.903151  ...         0.063      0.300839   
17771  0.162791  0.111111  1.000000  ...         0.160      1.000000   

       usg%_max_opp  ortg_max_opp  drtg_max_opp  total_opp  home_opp    won  \
0          0.277279      0.554502      0.317647   0.451923       1.0  False   
1          0.160462      0.345972      0.317647   0.317308       1.0  False   
2          0.088575      0.232227      0.329412   0.298077       0.0   True   
3          0.215661      0.530806      0.505882   0.298077       0.0   True   
4          0.019255      0.203791      0.317647   0.403846       0.0  False   
...             ...           ...           ...        ...       ...    ...   
17767      0.182285      0.208531      0.411765   0.413462       0.0  False   
17768      0.928113      1.000000      0.411765   0.288462       0.0   True   
17769      0.181001      0.630332      0.352941   0.384615       1.0  False   
17770      0.120668      0.459716      0.400000   0.375000       0.0  False   
17771      0.263158      0.246445      0.576471   0.250000       1.0   True   

       team  season  
0       NOP    2016  
1       CLE    2016  
2       CHI    2016  
3       GSW    2016  
4       ATL    2016  
...     ...     ...  
17767   BOS    2022  
17768   GSW    2022  
17769   BOS    2022  
17770   BOS    2022  
17771   GSW    2022  

[17772 rows x 139 columns]